# Generated by Django 4.1.5 on 2023-01-24 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_shopper_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('adress_1', models.CharField(help_text='Adresse de voirie et numéro de rue.', max_length=1024)),
                ('adress_2', models.CharField(blank=True, help_text='Batiment, étage, lieu-dit.', max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('zip_code', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
